# Generated by Django 4.1.3 on 2022-11-12 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('binomotron', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apprenant',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='brief',
            name='pub_date',
        ),
    ]
