# Generated by Django 4.1.3 on 2022-11-17 17:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binomotron', '0003_brief_date_debut_brief_date_fin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brief',
            name='date_debut',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 17, 17, 57, 25, 460061, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='brief',
            name='date_fin',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 17, 17, 57, 25, 460371, tzinfo=datetime.timezone.utc)),
        ),
    ]
