# Generated by Django 4.1.3 on 2022-11-17 17:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binomotron', '0004_alter_brief_date_debut_alter_brief_date_fin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brief',
            name='date_debut',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 17, 17, 59, 30, 727774, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='brief',
            name='date_fin',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 17, 17, 59, 30, 728229, tzinfo=datetime.timezone.utc)),
        ),
    ]
