# Generated by Django 4.1.3 on 2022-11-18 11:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('binomotron', '0007_alter_brief_date_debut_alter_brief_date_fin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brief',
            name='date_debut',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='brief',
            name='date_fin',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
