# Generated by Django 4.1.3 on 2022-11-19 17:57

import binomotron.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binomotron', '0009_alter_brief_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brief',
            name='date_debut',
            field=models.DateField(default=datetime.datetime(2022, 11, 19, 17, 57, 20, 138637, tzinfo=datetime.timezone.utc), validators=[binomotron.models.validate_datedebut]),
        ),
        migrations.AlterField(
            model_name='brief',
            name='date_fin',
            field=models.DateField(default=datetime.datetime(2022, 11, 19, 17, 57, 20, 138674, tzinfo=datetime.timezone.utc)),
        ),
    ]
