# Generated by Django 4.1.3 on 2022-11-19 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binomotron', '0011_alter_brief_date_debut_alter_brief_date_fin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brief',
            name='lien',
            field=models.URLField(unique=True),
        ),
    ]
